static char* asciiart = "\n"
"   SSSSSSSSSSSSSSS                                  tttt                                                                    \n"
"   SS:::::::::::::::S                              ttt:::t                                                                  \n"
"  S:::::SSSSSS::::::S                              t:::::t                                                                  \n"
"  S:::::S     SSSSSSS                              t:::::t                                                                  \n"
"  S:::::S                 aaaaaaaaaaaaa     ttttttt:::::ttttttt       uuuuuu    uuuuuu    rrrrr   rrrrrrrrr      nnnn  nnnnnnnn     \n"
"  S:::::S                 a::::::::::::a    t:::::::::::::::::t       u::::u    u::::u    r::::rrr:::::::::r     n:::nn::::::::nn   \n"
"   S::::SSSS              aaaaaaaaa:::::a   t:::::::::::::::::t       u::::u    u::::u    r:::::::::::::::::r    n::::::::::::::nn  \n"
"    SS::::::SSSSS                  a::::a   tttttt:::::::tttttt       u::::u    u::::u    rr::::::rrrrr::::::rn   n:::::::::::::::n \n"
"      SSS::::::::SS         aaaaaaa:::::a         t:::::t             u::::u    u::::u     r:::::r     r:::::r     n:::::nnnn:::::n \n"
"         SSSSSS::::S      aa::::::::::::a         t:::::t             u::::u    u::::u     r:::::r     rrrrrrr     n::::n    n::::n \n"
"              S:::::S    a::::aaaa::::::a         t:::::t             u::::u    u::::u     r:::::r                 n::::n    n::::n \n"
"              S:::::S   a::::a    a:::::a         t:::::t    tttttt   u:::::uuuu:::::u     r:::::r                 n::::n    n::::n \n"
"  SSSSSSS     S:::::S   a::::a    a:::::a         t::::::tttt:::::t   u:::::::::::::::uu   r:::::r                 n::::n    n::::n \n"
"  S::::::SSSSSS:::::S   a:::::aaaa::::::a         tt::::::::::::::t    u:::::::::::::::u   r:::::r                 n::::n    n::::n \n"
"  S:::::::::::::::SS     a::::::::::aa:::a          tt:::::::::::tt     uu::::::::uu:::u   r:::::r                 n::::n    n::::n \n"
"   SSSSSSSSSSSSSSS        aaaaaaaaaa  aaaa            ttttttttttt         uuuuuuuu  uuuu   rrrrrrr                 nnnnnn    nnnnnn \n\n"
"             Xenon Linux Loader Reloaded v0.993, Saturn Edition\n";

static char* asciitail =
"    Special Corona & Winchester Compatible XeLL version\n\n"
"    Presenting the Beth Special\n"
"    Greetings to: Octal450, JustAnyone, Juan, InvoxiPlayGames, GrimDoomer, Swizzy, 15432, MrMario2011 Project Free60\n"
"    Fuck You MTW\n"
"    Rest in Peace Jimmy, you were a dear friend, We won't forget what you did for us\n"
"    Pimps At Sea Lives Forever\n\n";